FROM node:16-alpine

WORKDIR '/app'

COPY ./package.json .
RUN npm install

# This copy statement is not required if you're using
# docker-compose.yml and referencing volumes
COPY . .

CMD ["npm", "run", "start"]